name: farmer_mall_app
description: Farmer Mall Flutter App (Orange + White theme)

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.3
  shared_preferences: ^2.0.18
  provider: ^6.0.5
  socket_io_client: ^2.0.0
  flutter_spinkit: ^5.1.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

# assets (if you later add icons/images)
flutter:
  uses-material-design: true
  assets:
    - assets/

# App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "web/favicon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "web/favicon.png"
